# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"



#gem 'rspec', '~> 3.1.0'

gem 'rspec-puppet'

# gem 'inspec'

# gem install rubygems-update
# update_rubygems
# gem update --system