forge 'https://forge.puppet.com'

# Modules discovered by generate-puppetfile
mod 'puppetlabs/ntp',    '7.0.0'
mod 'puppetlabs/stdlib', '4.24.0'
mod 'biemond/wildfly', :git => 'https://github.com/biemond/biemond-wildfly'
mod 'jethrocarr/initfact'
mod 'puppetlabs/apache'
mod 'puppetlabs/java'
mod 'puppetlabs/postgresql'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'maestrodev-wget', '1.7.3'
mod 'maestrodev-maven', '1.4.0'
